export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const FETCH_DELIVERY ='FETCH_DELIVERY';
export const FETCH_DELIVERY_SUCCESS ='FETCH_DELIVERY_SUCCESS';
export const FETCH_DELIVERY_FAIL ='FETCH_DELIVERY_FAIL';